apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring-boot-app
  namespace: spring-boot

spec:
  template:
    metadata:
      name: spring-boot
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot
        image: registry.prashanthgr.private:5000/spring-boot-app:v1.0.0
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
